name: sampletest

on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile Java code
        run: |
          javac src/com/te/Samp.java

      - name: Run Java class
        run: |
          java -cp src/com/te/Samp.java


